In [2]:
import numpy as np

## DataTypes & Attributes

In [3]:
# NumPy's main datatype is nd.array, or n-dimensional array
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1, 2.5, 3.4], [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])

In [6]:
a1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [8]:
a3.shape

(3, 2, 3)

In [9]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [10]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [11]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [12]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [13]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

,0,1,2
0,1.0,2.5,3.4
1,4.0,5.0,6.5


## 2. Creating arrays

In [14]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [15]:
sample_array.dtype

dtype('int64')

In [16]:
ones = np.ones((2,3))

In [17]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
ones.dtype

dtype('float64')

In [19]:
type(ones)

numpy.ndarray

In [20]:
zeros = np.zeros((2, 3))

In [21]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [23]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[9, 4, 1, 6, 2],
       [9, 4, 6, 3, 0],
       [7, 9, 4, 4, 6]])

In [24]:
random_array.size

15

In [25]:
random_array.shape

(3, 5)

In [26]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.56893697, 0.03970805, 0.07529538],
       [0.20677816, 0.63548492, 0.1476275 ],
       [0.29129213, 0.1762027 , 0.47048715],
       [0.05454748, 0.3425654 , 0.54693355],
       [0.84979764, 0.75565105, 0.95483713]])

In [27]:
random_array_2.shape

(5, 3)

In [28]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.41717494, 0.72699474, 0.41690595],
       [0.35340192, 0.93819729, 0.6499953 ],
       [0.54787105, 0.09482971, 0.84838819],
       [0.85842982, 0.58341685, 0.6448427 ],
       [0.23624955, 0.15128552, 0.10118803]])

In [29]:
# Psuedo-random numbers
np.random.seed(seed=0)

random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [30]:
random_array_4.shape

(5, 3)

In [31]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [32]:
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

## 3. Viewing arrays and matrices

In [34]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
a1

array([1, 2, 3])

In [36]:
a2

array([[1. , 2.5, 3.4],
       [4. , 5. , 6.5]])

In [37]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [40]:
a1[0]

np.int64(1)

In [41]:
a2[0]

array([1. , 2.5, 3.4])

In [42]:
a2.shape

(2, 3)

In [43]:
a3.shape

(3, 2, 3)

In [44]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [46]:
a2[1]

array([4. , 5. , 6.5])

In [47]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [48]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [49]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [50]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)