In [3]:
import numpy as np

## DataTypes & Attributes

In [4]:
# NumPy's main datatype is nd.array, or n-dimensional array
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1, 2.5, 3.4], [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(3, 2, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

,0,1,2
0,1.0,2.5,3.4
1,4.0,5.0,6.5


## 2. Creating arrays

In [16]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int64')

In [19]:
ones = np.ones((2,3))

In [20]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
ones.dtype

dtype('float64')

In [22]:
type(ones)

numpy.ndarray

In [24]:
zeros = np.zeros((2, 3))

In [25]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [28]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[5, 1, 5, 9, 6],
       [4, 8, 3, 5, 3],
       [9, 7, 4, 8, 5]])

In [29]:
random_array.size

15

In [30]:
random_array.shape

(3, 5)

In [31]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.33782792, 0.99538388, 0.87709082],
       [0.63576062, 0.18831981, 0.914603  ],
       [0.46985061, 0.36102877, 0.55340218],
       [0.13909272, 0.68050909, 0.2696842 ],
       [0.8971873 , 0.20564507, 0.93614941]])

In [32]:
random_array_2.shape

(5, 3)

In [33]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.06107109, 0.36078348, 0.07054434],
       [0.88187702, 0.05266979, 0.81653144],
       [0.91676708, 0.43799424, 0.25935689],
       [0.33446646, 0.62912633, 0.86879551],
       [0.0045475 , 0.99120926, 0.15265816]])

In [ ]:
# Psuedo-random numbers
np.random.seed()